/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Product, ProductWithPrice } from "./components/prysmex-pricing-table/prysmex-pricing-table";
import { Translations } from "./utils/locale";
import { Product as Product1 } from "./components/prysmex-pricing-table/prysmex-pricing-table";
export { Product, ProductWithPrice } from "./components/prysmex-pricing-table/prysmex-pricing-table";
export { Translations } from "./utils/locale";
export { Product as Product1 } from "./components/prysmex-pricing-table/prysmex-pricing-table";
export namespace Components {
    interface HighlightedProduct {
        "lang": string;
        "onClick": (product: Product) => void;
        "product": Product;
    }
    interface OneProduct {
        "lang": string;
        "onClick": (_product: ProductWithPrice) => void;
        "product": ProductWithPrice;
        "translations": Translations;
    }
    interface PrysmexPricingTable {
        "extraProducts": Product1[];
        /**
          * The products
         */
        "products": Product1[];
        "translations": Translations;
    }
}
declare global {
    interface HTMLHighlightedProductElement extends Components.HighlightedProduct, HTMLStencilElement {
    }
    var HTMLHighlightedProductElement: {
        prototype: HTMLHighlightedProductElement;
        new (): HTMLHighlightedProductElement;
    };
    interface HTMLOneProductElement extends Components.OneProduct, HTMLStencilElement {
    }
    var HTMLOneProductElement: {
        prototype: HTMLOneProductElement;
        new (): HTMLOneProductElement;
    };
    interface HTMLPrysmexPricingTableElement extends Components.PrysmexPricingTable, HTMLStencilElement {
    }
    var HTMLPrysmexPricingTableElement: {
        prototype: HTMLPrysmexPricingTableElement;
        new (): HTMLPrysmexPricingTableElement;
    };
    interface HTMLElementTagNameMap {
        "highlighted-product": HTMLHighlightedProductElement;
        "one-product": HTMLOneProductElement;
        "prysmex-pricing-table": HTMLPrysmexPricingTableElement;
    }
}
declare namespace LocalJSX {
    interface HighlightedProduct {
        "lang"?: string;
        "onClick"?: (product: Product) => void;
        "product"?: Product;
    }
    interface OneProduct {
        "lang"?: string;
        "onClick"?: (_product: ProductWithPrice) => void;
        "product"?: ProductWithPrice;
        "translations"?: Translations;
    }
    interface PrysmexPricingTable {
        "extraProducts"?: Product1[];
        /**
          * The products
         */
        "products"?: Product1[];
        "translations"?: Translations;
    }
    interface IntrinsicElements {
        "highlighted-product": HighlightedProduct;
        "one-product": OneProduct;
        "prysmex-pricing-table": PrysmexPricingTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "highlighted-product": LocalJSX.HighlightedProduct & JSXBase.HTMLAttributes<HTMLHighlightedProductElement>;
            "one-product": LocalJSX.OneProduct & JSXBase.HTMLAttributes<HTMLOneProductElement>;
            "prysmex-pricing-table": LocalJSX.PrysmexPricingTable & JSXBase.HTMLAttributes<HTMLPrysmexPricingTableElement>;
        }
    }
}
